apiVersion: apps/v1
kind: Deployment
metadata:
  name: gemini-fe-app
  labels:
    app: gemini-fe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gemini-fe-app
  template:
    metadata:
      labels:
        app: gemini-fe-app
    spec:
      containers:
      - name: gemini-fe-app
        image: gcr.io/$PROJECT_ID/gemini-fe:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gemini-fe-app
spec:
  type: LoadBalancer
  selector:
    app: gemini-fe-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
